### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SuperTux88** [comment]
:cookie:

**Comment by ghost** [comment]
https://wiki.freedesktop.org/www/Software/systemd/ have a look at this page. You have to write "systemd" with with a lower case 's'

**Comment by SuperTux88** [comment]
Can you please change this in the pom.xml too.

**Comment by ghost** [comment]
No, this changes are not planned in the current sprint. I'll open a seperate pull request when the next sprint starts.

**Comment by dr03lf** [comment]
🐔

**Comment by ghost** [comment]
bump.

**Pull request closed without merging**
